name: Create a comment on new issues

on: 
  issues: 
    types:  [opened]

jobs:
  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: "comment with Github API"
        run: |
          gh api -X POST \
            https://api.github.com/repo/${ORGANIZATION}/${REPOSITORY}/issues/{$ISSUE_NUMBER}/comments\
            -f body='
            this is my comment'
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          ORGANIZATION: ${{ github.event.organization.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}

#  comment-with-action:
 #   runs-on: ubuntu-latest
  #  steps:
   #   - name: "dump github context"
    #    run: echo '${{ toJSON(github.event)  }}' | jq
#        shell: bash 
 #     - name: Add comment
  #      uses: peter-evans/create-or-update-comment@v3
   #     with:
    #      issue-number: 1
     #     body: |
      #      This is a multi-line test comment
       #   reactions: '+1'
